spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ffxarcher/configServer
          username: saber1010137@gmail.com
          password: ffx10101fsn
          basedir:  /Users/shuaiqi/IdeaProjects/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
